### ISSUE TITLE
Allow Specification of ENV Vars in the Scan CRD

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox-v2-alpha#48]
**Is your feature request related to a problem? Please describe.**

When wanting to use confidential data in a Scan you currently have to include this confidential information in the scan itself, or create a new ScanType which mounts this data from a kubernetes secret.

**Describe the solution you'd like**

The Scan CRD should allow to add additional environment vars. E.g:

```yaml
apiVersion: "execution.experimental.securecodebox.io/v1"
kind: Scan
metadata:
  name: "nmap-from-secret"
spec:
  scanType: "nmap"
  env:
    - name: TARGET
      valueFrom:
        secretKeyRef:
          name: example-secret
          key: target
  parameters:
    - "-p22,443"
    - "$(TARGET)"
```

**Describe alternatives you've considered**

- Create a new ScanType which mounts this data from a kubernetes secret
