### ISSUE TITLE
Declarative scan hook is failing in combination with scheduled scans

### ISSUE THREAD

**Issue by rfelber** [secureCodeBox/secureCodeBox-v2-alpha#62]
**Describe the bug**
Using _scheduledScans_ in combination with an installed _declarative-scan-hook_ will always fail, even if no cascading is defined in the _scanSpec_.

**To Reproduce**

1. Create a new namespace like _demo-scans_
2. Install the _nmap scanType_ via helm into the namespace
3. Install the demo-apps via helm into the namespace
4. Install the _declarative-scan-hook_ via helm into the namespace
5. Apply a _ScheduledScan_ to your namespace (with installed demo-targets in a namespace):

```yaml
apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ScheduledScan
metadata:
  name: "nmap-cascading-dummy-ssh"
  namespace: demo-scans
  labels:
    organization: "Demo"
    product: "kubernetes"
    attack-surface: internal
spec:
  interval: 24h
  historyLimit: 1
  scanSpec:
    scanType: "nmap"
    parameters:
      # Internal cluster is blocking our ping probes, therefore we skip them
      - "-Pn"
      # Service Detection enabled
      - "-sV"
      # Actual Service Address will depend on you cluster and namespace configuration. 🤷‍
      - "dummy-ssh.demo-scans.svc"
```
6. Check the errored pod of the hook: `kubectl logs dssh-declarative-subsequent-scans-nmap-cascading-dummy-ss-qknrw -n demo-scans`

```bash
Starting hook for Scan "nmap-cascading-dummy-ssh-1595498493"
Fetched 2 findings from the file storage
Fetching CascadingScans using LabelSelector: "securecodebox.io/intensive=light"
Fetched 9 CascadingRules
Error was thrown while running hooks handle function
TypeError: Cannot read property 'cascading.securecodebox.io/chain' of undefined
    at getCascadingScans (/home/app/hook-wrapper/hook/hook.js:111:40)
    at /home/app/hook-wrapper/hook/hook.js:66:38
    at step (/home/app/hook-wrapper/hook/hook.js:44:23)
    at Object.next (/home/app/hook-wrapper/hook/hook.js:25:53)
    at fulfilled (/home/app/hook-wrapper/hook/hook.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

7. Apply another _ScheduledScan_ to your namespace (with installed demo-targets in a namespace):

```yaml
apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ScheduledScan
metadata:
  name: "nmap-cascading-bodgeit"
  namespace: demo-scans
  labels:
    organization: "Demo"
    product: "kubernetes"
    attack-surface: internal
spec:
  interval: 24h
  historyLimit: 1
  scanSpec:
    scanType: "nmap"
    parameters:
      # Internal cluster is blocking our ping probes, therefore we skip them
      - "-Pn"
      # Service Detection enabled
      - "-sV"
      # Actual Service Address will depend on you cluster and namespace configuration. 🤷‍
      - "bodgeit.demo-scans.svc"
      cascades:
        matchLabels:
          securecodebox.io/intensive: light
```

8. Check the errored pod of the hook: `kubectl logs dssh-declarative-subsequent-scans-nmap-cascading-bodgeit--7lgs9 -n demo-scans`

```
Starting hook for Scan "nmap-cascading-bodgeit-1595499882"
Fetched 2 findings from the file storage
Skipping cascades as no selector was defined.
Error was thrown while running hooks handle function
TypeError: Cannot read property 'cascading.securecodebox.io/chain' of undefined
    at getCascadingScans (/home/app/hook-wrapper/hook/hook.js:111:40)
    at /home/app/hook-wrapper/hook/hook.js:66:38
    at step (/home/app/hook-wrapper/hook/hook.js:44:23)
    at Object.next (/home/app/hook-wrapper/hook/hook.js:25:53)
    at fulfilled (/home/app/hook-wrapper/hook/hook.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Expected behavior**
It should be possible to use the _delcarative-scan-hook_ in combination with _ScheduledScan_ Types.
